### ISSUE TITLE
Observability Ressource

### ISSUE THREAD

**Issue by tux1980** [michaelkotelnikov/rhacm-workshop#3]
Hi, I can't create the Observability Ressource with OCP 4.8.13. 

Command:
oc apply -f https://raw.githubusercontent.com/michaelkotelnikov/rhacm-workshop/master/03.Observability/exercise/multiclusterobservability.yaml -n open-cluster-management-observability

Error:
error: unable to recognize "https://raw.githubusercontent.com/michaelkotelnikov/rhacm-workshop/master/03.Observability/exercise/multiclusterobservability.yaml": no matches for kind "MultiClusterObservability" in version "observability.open-cluster-management.io/v1beta1"

Maybe wrong API version in this OCP Version?

Thanks!
Wolfgang

**Comment by michaelkotelnikov** [comment]
Hey @tux1980 the workshop version has been updated, everything should be in order with rhacm 2.5.0 and openshift 4.10 :)

**Comment by tux1980** [comment]
Thanks a lot! I did update to the last release 2.5 days ago and I'm going to test it out! best regards
